### ISSUE TITLE
composer?

### ISSUE THREAD

**Issue by steveheinsch** [oblogic7/tlog-php#1]
Is this on packagist? I couldn't locate it there and composer wouldn't install it (composer require oblogic7/tlog-php)

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - The requested package oblogic7/tlog-php could not be found in any version, there may be a typo >in the package name.

**Comment by oblogic7** [comment]
Added to packagist.
