### ISSUE TITLE
Can't get to install via composer

### ISSUE THREAD

**Issue by steveheinsch** [oblogic7/tlog-php#2]
I'm sorry, no matter what I try I can't get this package to install.

> composer require oblogic7/tlog-php
> 
>  [InvalidArgumentException]
>  Could not find package oblogic7/tlog-php at any version for your minimum-stability (stable). Ch
>  eck the package spelling or your minimum-stability

**Comment by oblogic7** [comment]
`Check the package spelling or your minimum-stability`

You need to set your minimum stability to "dev".

**Comment by steveheinsch** [comment]
Thanks, adding "minimum-stability": "dev" in the options section of composer.json in the project root didn't help, or any of the other things I've tried. I haven't run into this issue before, although I really don't use composer much. I'll have to try again later when I have some free time to try to figure this out.

**Comment by steveheinsch** [comment]
I'm sorry, in the "config" section, not "options"

**Comment by oblogic7** [comment]
To get started quickly you can do a `composer init` and fill out details for your project as prompted.  That should generate a composer.json file for you.  It will allow you to define dependencies in that interactive process, but if it doesn't find the package you can do it back on the command line with `composer require oblogic7/tlog-php`.

You can manually edit the composer.json file and add `"minimum-stability": "dev"` in the root level.

**Comment by steveheinsch** [comment]
Thanks, I added "oblogic7/tlog-php": "@dev"
